
### Data cleaning and Classification 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("adult.csv")
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [3]:
df.columns = ['Age','Workclass','Fnlwgt','Education','education_num','marital_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week','native_country','income']

In [4]:
df.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [6]:
df.shape

(32560, 15)

In [9]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [10]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [11]:
df['Workclass'].value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1297
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64

In [12]:
df['Education'].value_counts()

 HS-grad         10501
 Some-college     7291
 Bachelors        5354
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: Education, dtype: int64

In [14]:
df['marital_status'].value_counts()

 Married-civ-spouse       14976
 Never-married            10682
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse           23
Name: marital_status, dtype: int64

In [15]:
df['relationship'].value_counts()

 Husband           13193
 Not-in-family      8304
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: relationship, dtype: int64

In [16]:
df['occupation'].value_counts()

 Prof-specialty       4140
 Craft-repair         4099
 Exec-managerial      4066
 Adm-clerical         3769
 Sales                3650
 Other-service        3295
 Machine-op-inspct    2002
 ?                    1843
 Transport-moving     1597
 Handlers-cleaners    1370
 Farming-fishing       994
 Tech-support          928
 Protective-serv       649
 Priv-house-serv       149
 Armed-Forces            9
Name: occupation, dtype: int64

In [17]:
df['race'].value_counts()

 White                 27815
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
Name: race, dtype: int64

In [18]:
df['sex'].value_counts()

 Male      21789
 Female    10771
Name: sex, dtype: int64

In [19]:
df['native_country'].value_counts()

 United-States                 29169
 Mexico                          643
 ?                               583
 Philippines                     198
 Germany                         137
 Canada                          121
 Puerto-Rico                     114
 El-Salvador                     106
 India                           100
 Cuba                             95
 England                          90
 Jamaica                          81
 South                            80
 China                            75
 Italy                            73
 Dominican-Republic               70
 Vietnam                          67
 Guatemala                        64
 Japan                            62
 Poland                           60
 Columbia                         59
 Taiwan                           51
 Haiti                            44
 Iran                             43
 Portugal                         37
 Nicaragua                        34
 Peru                             31
 

In [20]:
df['income'].value_counts()

 <=50K    24719
 >50K      7841
Name: income, dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
lb= LabelEncoder()

In [24]:
df['sex']=lb.fit_transform(df['sex'])
df['income']=lb.fit_transform(df['income'])
df['Workclass']=lb.fit_transform(df['Workclass'])
df['marital_status']=lb.fit_transform(df['marital_status'])
df['race']=lb.fit_transform(df['race'])

In [25]:
df['sex'].value_counts()

1    21789
0    10771
Name: sex, dtype: int64

In [26]:
df['income'].value_counts()

0    24719
1     7841
Name: income, dtype: int64

In [28]:
df['Workclass'].value_counts()

4    22696
6     2541
2     2093
0     1836
7     1297
5     1116
1      960
8       14
3        7
Name: Workclass, dtype: int64

In [29]:
df['race'].value_counts()

4    27815
2     3124
1     1039
0      311
3      271
Name: race, dtype: int64

In [30]:
df['marital_status'].value_counts()

2    14976
4    10682
0     4443
5     1025
6      993
3      418
1       23
Name: marital_status, dtype: int64

In [31]:
df.dtypes

Age                int64
Workclass          int32
Fnlwgt             int64
Education         object
education_num      int64
marital_status     int32
occupation        object
relationship      object
race               int32
sex                int32
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income             int32
dtype: object

In [32]:
# excluding Education,occupation,relationship,native_country,fnlwgt
df.head()

Age  Workclass  Fnlwgt   Education  education_num  marital_status  \
0   50          6   83311   Bachelors             13               2   
1   38          4  215646     HS-grad              9               0   
2   53          4  234721        11th              7               2   
3   28          4  338409   Bachelors             13               2   
4   37          4  284582     Masters             14               2   

           occupation    relationship  race  sex  capital_gain  capital_loss  \
0     Exec-managerial         Husband     4    1             0             0   
1   Handlers-cleaners   Not-in-family     4    1             0             0   
2   Handlers-cleaners         Husband     2    1             0             0   
3      Prof-specialty            Wife     2    0             0             0   
4     Exec-managerial            Wife     4    0             0             0   

   hours_per_week  native_country  income  
0              13   United-States       0  
1              40   United-States       0  
2              40   United-States       0  
3              40            Cuba       0  
4              40   United-States       0

In [37]:
x=df.iloc[:,[0,1,4,5,8,9,10,11,12]]
y=df.iloc[:,-1]
print(x.shape)
print(y.shape)

(32560, 9)
(32560,)


In [35]:
from sklearn.model_selection import train_test_split 

In [38]:
x_tr,x_te,y_tr,y_te = train_test_split(x,y,test_size=0.25)
print(x_tr.shape)
print(x_te.shape)
print(y_tr.shape)
print(y_te.shape)

(24420, 9)
(8140, 9)
(24420,)
(8140,)


In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix ,classification_report 

In [46]:
def apply (model,x_tr,x_te,y_tr,y_te):
    model.fit(x_tr,y_tr)
    ypred=model.predict(x_te)
    print(ypred)
    print ('training score ',model.score(x_tr,y_tr))
    print ('testing score ',model.score(x_te,y_te))
    cm=confusion_matrix(y_te,ypred)
    print ('confusion matrix\n ',cm)
    print ('classification report\n ',classification_report(y_te,ypred))

a.decisionTreeclassifier

In [41]:
a=DecisionTreeClassifier(criterion='gini',max_depth=6,min_samples_split=29)
apply(a,x_tr,x_te,y_tr,y_te)

[0 1 0 ... 0 0 0]
training score  0.852989352989353
testing score  0.8539312039312039
confusion matrix
  [[5935  313]
 [ 876 1016]]
classification report
                precision    recall  f1-score   support

           0       0.87      0.95      0.91      6248
           1       0.76      0.54      0.63      1892

    accuracy                           0.85      8140
   macro avg       0.82      0.74      0.77      8140
weighted avg       0.85      0.85      0.84      8140



In [78]:
#validating precision,recall,calculating miscalculation
recall =5935/(5935+313)
print('recall:',recall)
precision=5935/(5935+876)
print('precision:',precision)
misclassification = (313+876)/(5935+313+876+1016)
print('the misclassification rate is:',misclassification)
accuracy=(5935+1016)/(5935+313+876+1016)
print('the accuracy is:',accuracy)
f1_score=2*precision*recall/(precision+recall)
print('the f1-score is',f1_score)

recall: 0.9499039692701664
precision: 0.8713845250330348
the misclassification rate is: 0.14606879606879608
the accuracy is: 0.8539312039312039
the f1-score is 0.9089516808331419


#b.Randomforest is the best model with 86% accuracy

In [48]:
b=RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=7,min_samples_split=21)
apply(b,x_tr,x_te,y_tr,y_te)

[0 1 0 ... 0 0 0]
training score  0.857084357084357
testing score  0.8563882063882063
confusion matrix
  [[5991  257]
 [ 912  980]]
classification report
                precision    recall  f1-score   support

           0       0.87      0.96      0.91      6248
           1       0.79      0.52      0.63      1892

    accuracy                           0.86      8140
   macro avg       0.83      0.74      0.77      8140
weighted avg       0.85      0.86      0.84      8140



In [77]:
#validating precision,recall,calculating miscalculation
recall =5991/(5991+257)
print('recall:',recall)
precision=5991/(5991+912)
print('precision:',precision)
misclassification = (912+257)/(5991+257+912+980)
print('the misclassification rate is:',misclassification)
accuracy=(5991+980)/(5991+980+257+912)
print('the accuracy is:',accuracy)
f1_score=2*precision*recall/(precision+recall)
print('the f1-score is',f1_score)

recall: 0.9588668373879642
precision: 0.867883528900478
the misclassification rate is: 0.1436117936117936
the accuracy is: 0.8563882063882063
the f1-score is 0.9111094213367804


#c.logisticregression

In [56]:
c=LogisticRegression(solver='liblinear')
apply(c,x_tr,x_te,y_tr,y_te)

[0 0 0 ... 0 0 0]
training score  0.8212940212940213
testing score  0.8275184275184275
confusion matrix
  [[5898  350]
 [1054  838]]
classification report
                precision    recall  f1-score   support

           0       0.85      0.94      0.89      6248
           1       0.71      0.44      0.54      1892

    accuracy                           0.83      8140
   macro avg       0.78      0.69      0.72      8140
weighted avg       0.82      0.83      0.81      8140



In [76]:
#validating precision,recall,calculating miscalculation
recall =5898/(5898+350)
print('recall:',recall)
precision=5898/(5898+1054)
print('precision:',precision)
misclassification = (350+1054)/(5898+350+1054+838)
print('the misclassification rate is:',misclassification)
accuracy=(5898+838)/(5898+350+1054+838)
print('the accuracy is:',accuracy)
f1_score=2*precision*recall/(precision+recall)
print('the f1-score is',f1_score)

recall: 0.9439820742637645
precision: 0.8483889528193326
the misclassification rate is: 0.17248157248157248
the accuracy is: 0.8275184275184275
the f1-score is 0.8936363636363637


#d.knnclassifier

In [58]:
d=KNeighborsClassifier(n_neighbors=23)
apply(d,x_tr,x_te,y_tr,y_te)

[0 1 0 ... 0 0 0]
training score  0.8622031122031122
testing score  0.85
confusion matrix
  [[5766  482]
 [ 739 1153]]
classification report
                precision    recall  f1-score   support

           0       0.89      0.92      0.90      6248
           1       0.71      0.61      0.65      1892

    accuracy                           0.85      8140
   macro avg       0.80      0.77      0.78      8140
weighted avg       0.84      0.85      0.85      8140



In [75]:
#validating precision,recall,calculating miscalculation
recall =5766/(5766+482)
print('recall:',recall)
precision=5766/(5766+739)
print('precision:',precision)
misclassification = (482+739)/(5766+482+739+1153)
print('the misclassification rate is:',misclassification)
accuracy=(5766+1153)/(5766+482+739+1153)
print('the accuracy is:',accuracy)
f1_score=2*precision*recall/(precision+recall)
print('the f1-score is',f1_score)

recall: 0.9228553137003841
precision: 0.8863950807071483
the misclassification rate is: 0.15
the accuracy is: 0.85
the f1-score is 0.9042578216890144


#e.svm

In [60]:
e=SVC(kernel='linear',C=0.1)
apply(e,x_tr,x_te,y_tr,y_te)

[0 0 0 ... 0 0 0]
training score  0.8004914004914004
testing score  0.8071253071253072
confusion matrix
  [[5851  397]
 [1173  719]]
classification report
                precision    recall  f1-score   support

           0       0.83      0.94      0.88      6248
           1       0.64      0.38      0.48      1892

    accuracy                           0.81      8140
   macro avg       0.74      0.66      0.68      8140
weighted avg       0.79      0.81      0.79      8140



In [74]:
recall =5851/(5851+397)
print('recall:',recall)
precision=5851/(5851+1173)
print('precision:',precision)
misclassification = (397+1173)/(5851+397+1173+719)
print('the misclassification rate is:',misclassification)
accuracy=(5851+719)/(5851+397+1173+719)
print('the accuracy is:',accuracy)
f1_score=1.56012/(0.93645+0.8330011)
print('the f1-score is',f1_score)

recall: 0.93645966709347
precision: 0.833001138952164
the misclassification rate is: 0.1928746928746929
the accuracy is: 0.8071253071253072
the f1-score is 0.8816971545582695
